---
- name: install bundler
  gem:
    name: "bundler"
    executable: "{{ rbenv_path }}/shims/gem"
    user_install: no

- name: ファイル(rails)を作成する
  file:
    path: /var/www/app/rails
    state: directory
    group: ec2-user
    owner: ec2-user


- name: ファイル(react)を作成する
  file:
    path: /var/www/app/react/tmp
    state: directory
    group: ec2-user
    owner: ec2-user

- name: 秘密鍵をデプロイ先にコピーする
  copy:
    src: "/home/ec2-user/.ssh/{{ git_secretkey }}"
    dest: /home/ec2-user/.ssh/

- name: 秘密鍵の権限を変更
  file:
    path: "/home/ec2-user/.ssh/{{ git_secretkey }}"
    group: ec2-user
    owner: ec2-user
    mode: 0600

- name: railsアプリをクローンする
  git:
    repo: "{{ app_backend }}"
    dest: /var/www/app/rails
    version: "{{ git_branch }}"
    key_file: "/home/ec2-user/.ssh/{{ git_secretkey }}"
    accept_hostkey: yes

- name: reactアプリをクローンする
  git:
    repo: "{{ app_frontend }}"
    dest: /var/www/app/react/tmp
    version: "{{ git_branch }}"
    key_file: "/home/ec2-user/.ssh/{{ git_secretkey }}"
    accept_hostkey: yes
    
   #- name: Gemfile書き換え
   #  replace:
   #    path: /var/www/app/rails/Gemfile
   #    regexp: ruby '3.0.0'
   #    replace: ruby '2.7.1'
   #
   #- name: .ruby-version書き換え
   #  replace:
   #    path: /var/www/app/rails/.ruby-version
   #    regexp: 3.0.0
   #    replace: 2.7.1

- name: chown -R  ec2-user rails
  file:
    path: /var/www/app/rails
    group: ec2-user
    owner: ec2-user
    recurse: yes
    state: directory

- name: bundle install
  shell: bash -lc "source {{ home_path }}/.bash_profile && bundle install"
  args: 
    chdir: /var/www/app/rails

- name: 環境変数PATHにrbenvのパスを設定
  blockinfile:
    dest: "{{ home_path }}/.bash_profile"
    create: yes
    insertafter: EOF
    marker: "# ANSIBLE MANAGED BLOCK for rds"
    content: export RAILS_DB_HOST={{ db_host  }}

- name: master.keyファイルを追加する
  file:
    path: /var/www/app/rails/config/master.key
    state: touch

- name: master.keyに情報を追加する    
  replace:
    path: /var/www/app/rails/config/master.key
    regexp: .*
    replace: "{{ masterkey }}"

- name: rails db:create RAILS_ENV=production
  shell: bash -lc "source {{ home_path }}/.bash_profile && bin/rails db:create RAILS_ENV=production"
  args:
    chdir: /var/www/app/rails

- name: rails db:create RAILS_ENV=production
  shell: bash -lc "source {{ home_path }}/.bash_profile && bin/rails db:migrate RAILS_ENV=production"
  args:
    chdir: /var/www/app/rails    

- name: reactアプリをクローンする
  git:
    repo: "{{ app_frontend }}"
    dest: /var/www/app/react/tmp
    version: "{{ git_branch }}"
    key_file: "/home/ec2-user/.ssh/{{ git_secretkey }}"
    accept_hostkey: yes        

- name: chown -R  ec2-user tmp
  file:
    path: /var/www/app/react/tmp
    group: ec2-user
    owner: ec2-user
    recurse: yes
    state: directory

- name: npm install
  shell: bash -lc  "source {{ home_path }}/.nvm/nvm.sh && npm install"
  args:
    chdir:  /var/www/app/react/tmp  
  become: no

- name: .envにEC2＿IPを記入する
  replace:
    path: /var/www/app/react/tmp/.env
    regexp: http.*
    replace: "http://{{ ec2_ip }}"

- name: npm run build
  shell: bash -lc "source {{ home_path }}/.nvm/nvm.sh && npm run build"
  args:
    chdir: /var/www/app/react/tmp

- name: mv build/* ..
  shell: bash -lc "mv -f build/* .."
  args:
    chdir: /var/www/app/react/tmp 
  ignore_errors: yes   
