---
# tasks file for nginx_install
  - name: Enable to nginx install
    shell: "amazon-linux-extras enable nginx1.12"

  - name: Install Nginx packages from amazon-linux-extras
    yum:
      name: nginx
      state: present

  - name: nginxのログ格納用ファイル作成
    file: 
     path: /var/www/app/nginx_log
     state: directory
     group: ec2-user
     owner: ec2-user

  - name: templatesからファイルごとnginx.confの書き換え
    template: 
      src: /var/lib/jenkins/workspace/execute_ansible/roles/nginx_install/templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf

  - name: templatesからアプリ固有設定ファイルを作成
    template:
      src: /var/lib/jenkins/workspace/execute_ansible/roles/nginx_install/templates/app.conf.j2
      dest: /etc/nginx/conf.d/app.conf
      force: no

  # nginxの起動
  - name: nginx start
    service:
      name: nginx
      state: started
      enabled: yes
  
  # nginxの状態確認
  - name: nginx status
    shell: "systemctl status nginx.service"
